FROM python:3.11-slim-bullseye

WORKDIR /app

# Install dependencies
COPY requirements.txt .
RUN apt-get update && apt-get upgrade -y && apt-get install -y --no-install-recommends gcc && \
	pip install --upgrade pip && \
	pip install -r requirements.txt && \
	apt-get purge -y --auto-remove gcc && \
	rm -rf /var/lib/apt/lists/*

# Install PyBuilder
RUN pip install pybuilder

# Copy all source code
COPY . .

# Run PyBuilder build
RUN pyb clean install

# Default command to run the bot
CMD ["python", "src/main/python/advisor/__main__.py"]
